# Use an official Python image
FROM python:3.12

# Set working directory
WORKDIR /app

# Copy the Python script into the image
COPY app.py .

# Run the script when the container starts
CMD ["python", "app.py"]